### ISSUE TITLE
naming conventionos

### ISSUE THREAD

**Issue by Tazinho** [gdemin/maditr#1]
Congrats to this very interesting package! I am just wondering about the naming conventions. Is there a reason they are not analogous to dplyr or sth. which is already established? Your conventions might be easier to adopt if you chose more similar verbs like i.e. `dt_filter`, `dt_select`, `dt_arrange` etc.

**Comment by gdemin** [comment]
There is a very thin layer over original data.table package and data.table has rather different syntax from dplyr. So data.table functions don't map one-to-one to dplyr verbs. For example, `take` is translated to `dt[, list(a, b)]`  or `dt[, list(sum(a), mean(b))]`  and it is an aggregation function and select column function simultaneously.  Sure, it is possible to translate dplyr functions to appropriate data.table calls but it is first version of the package and by now I prefer to keep things simple.  
However your suggestion sounds interesting so I will consider to add additional abstraction layer with dplyr verbs in the future version.

**Comment by Tazinho** [comment]
I think it's definitely good to stay simple at the beginning.
When comparing to dplyr this might be also of interest:
https://github.com/hadley/dtplyr

**Comment by gdemin** [comment]
Yes, I know about `dtplyr`. But it doesn't preserve `data.table` semantics such as in-place modification. It can lead to performance drop in some cases.
