### ISSUE TITLE
Want to write a dt_rename but failed

### ISSUE THREAD

**Issue by hope-data-science** [gdemin/maditr#11]
In `dplyr` there is a function called `rename`, while in `data.table` we have `setnames`.

Recently I tried to write a `dt_rename` and `dt_transmute` using `data.table` but failed. This should be easy, but I don't know how to let an R function to take an expression or multiple expressions, and melt and reorganized them. Is there some tricks?

Thanks.

**Comment by gdemin** [comment]
As a quick prototype:
```R
dt_rename = function(data, ...){
    if(!is.data.table(data)) data = as.data.table(data)
    all_names = list(...)
    setnames(data, old = unlist(all_names), new = names(all_names))
    data
}

dt_rename(mtcars, weight = "wt", displacement = "disp") %>% 
    head()
```

**Comment by hope-data-science** [comment]
Thank you for all the support, let's make more wonderful things in the future. This is the new work supported by `maditr`: <https://github.com/hope-data-science/tidydt>.
