### ISSUE TITLE
Conda forge r-maditr

### ISSUE THREAD

**Issue by jgraille** [gdemin/maditr#16]
Hello Gregory,

Thank you for this package. I was just wondering why there is no availability to get it from the conda `conda install -c conda-forge` command line. 
As a work around, I will try with the reshape2 package. I am using the `dcast()` function.

**Comment by gdemin** [comment]
Hi,
Sorry, I only submit this package to CRAN. And I don't know who supports conda repositories. Is it possible that you use outdated Anaconda/R version?

**Comment by mfansler** [comment]
@jgraille this has now been added. Install with `conda install -c conda-forge r-maditr`

@gdemin fyi, the Conda Forge feedstock tracks downstream of CRAN, so there's nothing you need to change about your workflow to maintain it. There are some badges that Conda Forge generates, in case you are interested in adding them to your README:

**Conda Forge Name**

[![Conda Recipe](https://img.shields.io/badge/recipe-r--maditr-green.svg)](https://anaconda.org/conda-forge/r-maditr) 

```
[![Conda Recipe](https://img.shields.io/badge/recipe-r--maditr-green.svg)](https://anaconda.org/conda-forge/r-maditr) 
```

**Downloads**

[![Conda Downloads](https://img.shields.io/conda/dn/conda-forge/r-maditr.svg)](https://anaconda.org/conda-forge/r-maditr)

```
[![Conda Downloads](https://img.shields.io/conda/dn/conda-forge/r-maditr.svg)](https://anaconda.org/conda-forge/r-maditr)
```

**Version**

[![Conda Version](https://img.shields.io/conda/vn/conda-forge/r-maditr.svg)](https://anaconda.org/conda-forge/r-maditr)

```
[![Conda Version](https://img.shields.io/conda/vn/conda-forge/r-maditr.svg)](https://anaconda.org/conda-forge/r-maditr)
```

**Available Platforms**

[![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/r-maditr.svg)](https://anaconda.org/conda-forge/r-maditr)

```
[![Conda Platforms](https://img.shields.io/conda/pn/conda-forge/r-maditr.svg)](https://anaconda.org/conda-forge/r-maditr)
```
