### ISSUE TITLE
Imports for data.table version are incorrect

### ISSUE THREAD

**Issue by spkaluzny** [gdemin/maditr#2]
Version 0.5.0 of maditr lists data.table (≥ 1.10) for Imports in the DESCRIPTION file. The maditr really needs data.table (>= 1.11). Otherwise the object groupingsets is not available from namespace:data.table

    install.packages("maditr")
    #> Installing package into ‘/home/R/site-library_R-3.4’
    #> (as ‘lib’ is unspecified)
    #> trying URL 'http://erratic/cran/src/contrib/maditr_0.5.0.tar.gz'
    #> Content type 'application/x-gzip' length 22693 bytes (22 KB)
    #> ==================================================
    #> downloaded 22 KB
    #>
    #> * installing *source* package ‘maditr’ ...
    #> ** package ‘maditr’ successfully unpacked and MD5 sums checked
    #> ** R
    #> ** inst
    #> ** preparing package for lazy loading
    #> Error : 'groupingsets' is not an exported object from 'namespace:data.table'
    #> Error : unable to load R code in package ‘maditr’
    #> ERROR: lazy loading failed for package ‘maditr’
    #> * removing ‘/home/R/site-library_R-3.4/maditr’
    packageVersion("data.table")
    #> [1] ‘1.10.4’

    sessionInfo()
    #> R version 3.4.3 (2017-11-30)
    #> Platform: x86_64-pc-linux-gnu (64-bit)
    #> Running under: Ubuntu 16.04.4 LTS
    #>
    #> Matrix products: default
    #> BLAS: /usr/lib/atlas-base/libf77blas.so.3.0
    #> LAPACK: /home/R/R-3.4.3/lib/R/lib/libRlapack.so
    #>
    #> locale:
    #>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C       
    #>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
    #>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
    #>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C          
    #>  [9] LC_ADDRESS=C               LC_TELEPHONE=C     
    #> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
    #>
    #> attached base packages:
    #> [1] stats     graphics  grDevices utils     datasets  methods   base
    #>
    #> loaded via a namespace (and not attached):
    #> [1] compiler_3.4.3 tools_3.4.3

**Comment by gdemin** [comment]
Thank you for your feedback.
I know about this bug. Will fix in the nearest future.

**Comment by gdemin** [comment]
Fixed in version v5.1
