### ISSUE TITLE
Return top row(s) by group

### ISSUE THREAD

**Issue by markfairbanks** [gdemin/maditr#6]
Is there a way to do this same command in maditr? It returns the top row by group.

```r
library(maditr)

dt <- data.table(x = c(1,2,3,4,5), y = c("a","a","a","b","b"))

dt[, head(.SD, 1), by = y]
```

**Comment by gdemin** [comment]
There is a `query` function which translates one-to-one its arguments to data.table:
```R
library(maditr)
dt <- data.table(x = c(1,2,3,4,5), y = c("a","a","a","b","b"))
query(dt, head(.SD, 1), by = y)
```
or, with `take`:
```R
take(dt, by = y, fun = first)
```
or, in dplyr style:
```R
dt_summarise_all(dt, first, by = y)
```

**Comment by markfairbanks** [comment]
That's great, `query()` is exactly what I was looking for. Thanks for the help!
